apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infraconfig
  annotations:
    argocd.argoproj.io/sync-wave: "102"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 1-infra/infraconfig
    repoURL: github.com/Jibbscript/multi-tenancy-gitops.git
    targetRevision: demo-mq-v2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
