apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ibm-gitops
  annotations:
    description: Publishes the helm chart configuration to the provided gitops repo to trigger downstream deployments
    app.openshift.io/description: Publishes the helm chart configuration to the provided gitops repo to trigger downstream deployments
    app.openshift.io/vcs-uri: https://github.com/IBM/ibm-garage-tekton-tasks
    app.openshift.io/vcs-ref: master
  labels:
    version: 0.0.0
spec:
  params:
    - name: app-name
      default: ""
    - name: version
      default: ""
    - name: environment
      default: ""
    - name: app-type
      default: ""
    - name: source-dir
      default: /source
    - name: subdir
      default: ""
    - name: parentdir
      default: ""
    - name: yaml
      default: "requirements.yaml"
    - name: helm-url
      default: ""
    - name: tools-image
      default: quay.io/ibmgaragecloud/ibmcloud-dev:v2.0.4
  volumes:
    - name: source
      emptyDir: {}
  stepTemplate:
    volumeMounts:
      - name: source
        mountPath: $(params.source-dir)
  steps:
    - name: gitops
      image: $(params.tools-image)
      workingDir: $(params.source-dir)
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOME
          value: /home/devops
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: username
              optional: true
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: password
              optional: true
        - name: GIT_USERNAME_CD
          valueFrom:
            secretKeyRef:
              name: gitops-cd-secret
              key: username
              optional: true
        - name: GIT_PASSWORD_CD
          valueFrom:
            secretKeyRef:
              name: gitops-cd-secret
              key: password
              optional: true
        - name: GIT_PARENT_DIR
          valueFrom:
            configMapKeyRef:
              name: gitops-repo
              key: parentdir
              optional: true
        - name: GIT_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: gitops-repo
              key: protocol
              optional: true
        - name: GIT_HOST
          valueFrom:
            configMapKeyRef:
              name: gitops-repo
              key: host
              optional: true
        - name: GIT_ORG
          valueFrom:
            configMapKeyRef:
              name: gitops-repo
              key: org
              optional: true
        - name: GIT_REPO
          valueFrom:
            configMapKeyRef:
              name: gitops-repo
              key: repo
              optional: true
        - name: GIT_BRANCH
          valueFrom:
            configMapKeyRef:
              name: gitops-repo
              key: branch
              optional: true
      script: |
          #!/usr/bin/env bash
          set -ex

          APP_NAME="$(params.app-name)"

          if [[ "${APP_NAME}" = "mq-infra" ]]; then
            APP_TYPE="2-services/instances"
          elif [[ "${APP_NAME}" = "mq-spring-app" ]]; then
            APP_TYPE="3-apps/instances"
          else
            APP_TYPE="App type does not exist"
          fi

          ENV=$(echo $(params.environment) | cut -d "-" -f2)

          SUBDIR="$(params.subdir)"
          if [[ -z "${SUBDIR}" ]]; then
            SUBDIR="${APP_NAME}"
          fi
          if [[ -n "$(params.parentdir)" ]]; then
            PARENT_DIR="$(params.parentdir)/$(params.app-type)/$(params.environment)"
          elif [[ -n "${GIT_PARENT_DIR}" ]] && [[ "${GIT_PARENT_DIR}" = "bash -c"* ]]; then
            PARENT_DIR=$(eval $GIT_PARENT_DIR | tail -n 1)"/$(params.app-type)/$(params.environment)"
          elif [[ -n "${GIT_PARENT_DIR}" ]]; then
            PARENT_DIR="${GIT_PARENT_DIR}/$(params.app-type)/$(params.environment)"
          else
            PARENT_DIR="."
          fi
          SUBDIR="${PARENT_DIR}/${SUBDIR}"

          PROTOCOL="${GIT_PROTOCOL}"
          if [[ -z "${PROTOCOL}" ]]; then
            PROTOCOL="https"
          fi

          YAML_FILE="$(params.yaml)"
          VERSION="$(params.version)"
          HELM_URL="$(params.helm-url)"

          if [[ -z "${GIT_HOST}" ]] || [[ -z "${GIT_ORG}" ]] || [[ -z "${GIT_REPO}" ]]; then
              echo "GitOps repo has not been configured with confimap gitops-repo. Skipping trigger step"
              exit 0
          fi

          set +x
          if [[ -n "${GIT_USERNAME_CD}" ]]; then
            GIT_AUTH_USER="${GIT_USERNAME_CD}"
            GIT_AUTH_PWD="${GIT_PASSWORD_CD}"
          elif [[ -n "${GIT_USERNAME}" ]]; then
            GIT_AUTH_USER="${GIT_USERNAME}"
            GIT_AUTH_PWD="${GIT_PASSWORD}"
          else
            echo "Credentials for GitOps repo not set in secret gitops-cd-secret or git-credentials"
            exit 1
          fi
          set -x

          BRANCH_CMD=""
          if [[ -n "${GIT_BRANCH}" ]]; then
            BRANCH_CMD="-b ${GIT_BRANCH}"
          fi

          git config --global user.email "gitops@cloudnativetoolkit.dev"
          git config --global user.name "Cloud Native Toolkit Pipeline"
          echo "git clone ${BRANCH_CMD} ${PROTOCOL}://${GIT_AUTH_USER}:xxxx@${GIT_HOST}/${GIT_ORG}/${GIT_REPO}"
          set +x
          GIT_URL="${PROTOCOL}://${GIT_AUTH_USER}:${GIT_AUTH_PWD}@${GIT_HOST}/${GIT_ORG}/${GIT_REPO}"
          git clone ${BRANCH_CMD} ${GIT_URL} gitops_cd
          set -x
          cd gitops_cd


          if [[ -f "${SUBDIR}/${YAML_FILE}" ]]; then
            echo "Requirements before update"
            cat "${SUBDIR}/${YAML_FILE}"

            yq r "${SUBDIR}/${YAML_FILE}" -j | \
              jq --arg APP_NAME "${APP_NAME}" --arg VERSION "${VERSION}" --arg REPO "${HELM_URL}" '.dependencies |= map((select(.name == $APP_NAME) | .version = $VERSION | .repository = $REPO) // .)' | \
              yq r --prettyPrint - > "${SUBDIR}/${YAML_FILE}.new"

            rm "${SUBDIR}/${YAML_FILE}"
            mv "${SUBDIR}/${YAML_FILE}.new" "${SUBDIR}/${YAML_FILE}"

            echo "Requirements after update"
            cat "${SUBDIR}/${YAML_FILE}"

          elif [[ -n "${HELM_URL}" ]]; then
            echo "Creating first time chart using ${SUBDIR}"
            # create directory
            mkdir -p "${SUBDIR}"

            # WARNING: Do not indent the cat commands below

          cat <<EOF >"${SUBDIR}/Chart.yaml"
          apiVersion: v2
          version: 0.1.0
          name: ${APP_NAME}
          description: Chart to configure ArgoCD with the ${APP_NAME} project and its applications
          dependencies:
            - name: argocd-hook-job
              version: 0.1.4
              repository: https://ibm-garage-cloud.github.io/toolkit-charts/
          EOF

          cat <<EOF >"${SUBDIR}/${YAML_FILE}"
          dependencies:
            - name: ${APP_NAME}
              version: ${VERSION}
              repository: >-
                ${HELM_URL}
            - name: argocd-hook-job
              version: 0.1.4
              repository: >-
                https://cloud-native-toolkit.github.io/toolkit-charts/
          EOF

          cat <<EOF >"${SUBDIR}/values.yaml"
          global: {}
          ${APP_NAME}:
            replicaCount: 1
          argocd-hook-job:
            name: postsync-trigger-for-${ENV}
            namespace: ci
            hook:
              enabled: true
              hooktype: PostSync
            hookdeletepolicy:
              enabled: true
              hookdeletepolicytype: HookSucceeded
            serviceaccount: pipeline-hook-argocd-hook-job
            roleaccess:
              - verbs:
                  - '*'
                apiGroups:
                  - 'tekton.dev'
                resources:
                  - pipelines
                  - tasks
            init:
              enabled: false
            container:
              image: "quay.io/rhcanada/tkn-cli"
              tag: "latest"
              command: "tkn"
              args:
                - -n
                - ci
                - pipeline
                - start
                - ibm-mq-promote-dev-stage
                - --param
                - src-environment="namespace-dev"
                - --param
                - dest-environment="namespace-staging"
                - --param
                - app-type="${APP_TYPE}"
                - --param
                - app-name="${APP_NAME}"
          EOF


          else
            echo "GitOps repo configured but unable to update application config"
            exit 1
          fi

          if [[ $(git status -s | wc -l) -eq 0 ]]; then
            echo "No changes"
            exit 0
          fi

          git add "${SUBDIR}/"
          git commit -m "Updates ${APP_NAME} to ${VERSION}"
          git push -v
