global: {}

ibm-aspera-operator:
  subscriptions:
    ibmaspera:
      name: ibm-aspera
      subscription:
        channel: v1.2-eus
        installPlanApproval: Automatic
        name: aspera-hsts-operator
        source: ibm-operator-catalog
        sourceNamespace: openshift-marketplace'