global: {}

subscriptions:
  cloudpakforintegration:
    name: ibm-cp-integration
    subscription:
      channel: v1.0
      installPlanApproval: Automatic
      name: ibm-cp-integration
      source: ibm-operator-catalog
      sourceNamespace: openshift-marketplace

  platformnavigator:
    name: ibm-integration-platform-navigator
    subscription:
      channel: v4.0
      installPlanApproval: Automatic
      name: ibm-integration-platform-navigator
      source: ibm-operator-catalog
      sourceNamespace: openshift-marketplace

instances:
  platformnavigator:
    name: integration-navigator
    license: true
    mqDashboard: true
    version: 2020.3.1
    replicas: 1
